#include <stdio.h>
#include <zenoh-pico.h>
#include "zenoh.h"

#include <esp_event.h>
#include <esp_log.h>
#include <esp_system.h>
#include <esp_wifi.h>
#include <esp_timer.h>
#include <freertos/FreeRTOS.h>
#include <freertos/semphr.h>
#include <freertos/event_groups.h>
#include <freertos/task.h>
#include <nvs_flash.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "utils.h"
#include "cnode.h"
#include "task.h"
#include "tboard.h"

/**
 * EXAMPLE FUNCTION THAT WE WANT TO ADD TO TBOARD
*/
int example (int a, int b, int c) {
    return 0;
}

/**
 * This function stub would be generated by the JamScript compiler 
*/
void entry_point_example(execution_context_t* context) {
    arg_t* args = context->query_args;
    int a = args[0].val.ival;
    int b = args[1].val.ival;
    int c = args[2].val.ival;
    int ret = example(a, b, c);
    // context->ret_arg.ival = ret;  // assume that ret_arg has already been allocated
    return;
}

void app_main(void)
{
    /**
     * TODO: FIND A WAY TO LINK THE FUNCTION POINTER (ENTRY POINT) TO THE TASK_T STRUCT
    */
    char* name = "example";
    uint32_t serial_id = 0;
    argtype_t return_type = INT_TYPE;
    char* fn_argsig = "iii"; 
    function_stub_t entry_point = entry_point_example;

    /* Create a task that takes in three integer parameters */
    task_t* task = task_create(name, serial_id, return_type, fn_argsig, entry_point);

    /* Now we can register the task using the task board */
    tboard_t* tboard = tboard_create();
    tboard_register_task(tboard, task);

    /* Imagine that we now want to run the task with the argument values (1, 2, 3) */

    /* Generate arguments */
    arg_t arg1 = {.type = INT_TYPE, .val.ival = 1};
    arg_t arg2 = {.type = INT_TYPE, .val.ival = 2};
    arg_t arg3 = {.type = INT_TYPE, .val.ival = 3};

    /* Set the args using variable arguments */
    task_set_args(task, 3, &arg1, &arg2, &arg3);

    /* Check that the args were correctly copied to task->args */
    arg_t** copy_args = task_get_args(task);
    if (copy_args != NULL) {
        printf("Read args: %d, %d, %d \r\n", copy_args[0]->val.ival, copy_args[1]->val.ival, copy_args[2]->val.ival);
    }

    /* In the future, we receive a command from another board to run this function with the given arguments */
    // command_process ...
    tboard_start_task(tboard, task->serial_id, copy_args);

    /* Display info about task */
    task_print(task);
    
    /* Wait for the task to finish */
    // while(!task->has_finished) {
    //     sleep(1);
    // };
    
    /* Return arguments will be placed in task->ret_arg */
    arg_t retarg = {.type = INT_TYPE, .val.ival = 0};
    task_set_return_arg(task, &retarg);

    /* Destroy task once its no longer in use */
    task_destroy(task);

    /* Loop forever */
    while (true) {
        sleep(1);
    }
}
